config/routes.rb
Waiters::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'  
  resources :hosts, :waiters, :events, :inquiries
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :event_date, :city, presence: true
  belongs_to :host
  has_and_belongs_to_many :waiters
end

app/models/host.rb
class Host < ActiveRecord::Base
  validates :name, :email, :phone, presence: true
  has_many :events
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  validates :name, :role, :city, :email, :phone, presence: true
end

app/models/waiter.rb
class Waiter < ActiveRecord::Base
  validates :name, :email, :phone, :city, presence: true
  has_and_belongs_to_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    respond_with(@event)
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_with(@event)
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.permit(:event_date, :city, hosts: [:id, :name, :phone, :email], waiters: [:id, :name, :phone, :email, :city])
    end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: [:show, :edit, :update, :destroy]

  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
  end

  # GET /hosts/new
  def new
    @host = Host.new
    @host.events.build
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(host_params)
    event = Event.new(event_params.merge(host: @host))

    respond_to do |format|
      if (@host.save && event.save)
        format.js { render action: "show", status: :created, location: @host }
      else
        format.js   { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1
  # PATCH/PUT /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to @host, notice: 'Host was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_params
      params.permit(:name, :email, :phone)
    end

    def event_params
      params.permit(:event_date, :city)
    end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
before_action :set_inquiry, only: [:show, :edit, :update, :destroy]
before_action :admin_user, only: [:index, :destroy, :show, :edit, :update]
  def index
    @inquiries = Inquiry.all
  end

  def show
  end

  def new
    @inquiry = Inquiry.new
  end

  def edit
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
  
    respond_to do |format|
      if (@inquiry.save)
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully created.' }
        format.json { render action: "show", status: :created, location: @inquiry }
      else
        format.html { render action: 'new' }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @inquiry.update(inquiry_params)
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inquiry.destroy
    respond_to do |format|
      format.html { redirect_to inquiries_url }
      format.json { head :no_content }
    end
  end

  private

    def set_inquiry
      @inquiry = Inquiry.find(params[:id])
    end

    def inquiry_params
      params.require(:inquiry).permit(:name, :role, :email, :phone, :city, :license, :date)
    end

    def admin_user
      redirect_to(root_url) unless current_admin_user
    end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  def create
    @signup = SignupForm.new(params[:signup])

    if @signup.save
      redirect_to root_path
    else
      render "new"
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @inquiry = Inquiry.new
  end
end

app/controllers/waiters_controller.rb
class WaitersController < ApplicationController
  before_action :set_waiter, only: [:show, :edit, :update, :destroy]

  # GET /waiters
  # GET /waiters.json
  def index
    @waiters = Waiter.all
  end

  # GET /waiters/1
  # GET /waiters/1.json
  def show
  end

  # GET /waiters/new
  def new
    @waiter = Waiter.new
  end

  # GET /waiters/1/edit
  def edit
  end

  # POST /waiters
  # POST /waiters.json
  def create
    @waiter = Waiter.new(waiter_params)

    respond_to do |format|
      if @waiter.save
        WaiterMailer.newwaiter_email(@waiter).deliver
         format.js { render action: 'show', status: :created, location: @waiter }
      else
        format.js { render action: 'new', status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waiters/1
  # PATCH/PUT /waiters/1.json
  def update
    respond_to do |format|
      if @waiter.update(waiter_params)
        format.html { redirect_to @waiter, notice: 'Waiter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @waiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waiters/1
  # DELETE /waiters/1.json
  def destroy
    @waiter.destroy
    respond_to do |format|
      format.html { redirect_to waiters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waiter
      @waiter = Waiter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waiter_params
      params.permit(:name, :email, :phone, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper 
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/waiters_helper.rb
module WaitersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :event_date %><br>
    <%= f.date_select :event_date %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <input name="commit" class="btn btn-danger" type="submit" value="Create Event" />
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Event date</th>
      <th>City</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.event_date %></td>
        <td><%= event.city %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>

<p>
  <strong>City:</strong>
  <%= @event.city %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/hosts/_form.html.erb
<%= form_for(@host, remote: :true) do |f| %>

  <div class="form-group">
    <label class="control-label" for="event_date">Event Date</label>
    <br />
    <input type="date" name="event_date" class="form-control" />
    <span class="help-block"></span>
  </div>

  <div class="form-group">
    <label class="control-label" for="city">City</label>
    <br />
    <input type="text" name="city" class="form-control" />
    <span class="help-block"></span>
  </div>

  <div class="form-group">
    <label class="control-label" for="name">Name</label>
    <br />
    <input type="text" name="name" class="form-control" />
    <span class="help-block"></span>
  </div>

  <div class="form-group">
    <label class="control-label" for="email">Email</label>
    <br />
    <input type="text" name="email" class="form-control" />
    <span class="help-block"></span>
  </div>

  <div class="form-group">
    <label class="control-label" for="phone">Phone</label>
    <br />
    <input type="text" name="phone" class="form-control" />
    <span class="help-block"></span>
  </div>

  <div class="actions">
    <input type="submit" name="commit" class="btn btn-danger" value="Submit" />
  </div>

<% end %>

app/views/hosts/edit.html.erb
<h1>Editing host</h1>

<%= render 'form' %>

<%= link_to 'Show', @host %> |
<%= link_to 'Back', hosts_path %>

app/views/hosts/index.html.erb
<h1>Listing hosts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @hosts.each do |host| %>
      <tr>
        <td><%= host.name %></td>
        <td><%= host.email %></td>
        <td><%= host.phone %></td>
        <td><%= link_to 'Show', host %></td>
        <td><%= link_to 'Edit', edit_host_path(host) %></td>
        <td><%= link_to 'Destroy', host, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Host', new_host_path %>

app/views/hosts/new.html.erb
<h1>New host</h1>

<%= render 'form' %>

<%= link_to 'Back', hosts_path %>

app/views/hosts/new.js.erb
$('div.form-group').addClass('has-error');
$('span').append('Try again.');

app/views/hosts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @host.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @host.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @host.phone %>
</p>

<%= link_to 'Edit', edit_host_path(@host) %> |
<%= link_to 'Back', hosts_path %>

app/views/hosts/show.js.erb
  $('span').empty();
  $('#myHostModal').modal('hide');
  document.getElementById("new_host").reset();
  $('#successMessage').append('Host was successfully created.').hide(3000);

app/views/inquiries/_form.html.erb
<%= simple_form_for @inquiry, 
  wrapper_mappings: {
    radio_buttons: :vertical_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean } do |f| %>
    <div class ="form-group radio_buttons required inquiry_role">
      <span class="radio">
        <input class="radio_buttons required" id="inquiry_role_hire" name="inquiry[role]" type="radio" value="Hire">
        <label for="inquiry_role_hire" name="inquiry[role]"><h2>Hire</h2></label>
      </span>
      <span class="radio">
        <input class="radio_buttons required" id="inquiry_role_work" name="inquiry[role]" type="radio" value="Work">
        <label for="inquiry_role_work" name="inquiry[role]"><h2>Work</h2></label>
      </span>
    </div>
    <div style="display: none;" data-show-for="both">
      <%= f.input :city %>
      <%= f.input :name %>
      <%= f.input :email, as: :email %>
      <%= f.input :phone, as: :tel %>
    </div>
    <div style="display: none;" data-show-for="Hire">
      <%= f.input :date, as: :date, :order => [:month, :day, :year], :include_blank => true %>
    </div>
    <div style="display: none;" data-show-for="Work">
      <%= f.input :license, as: :radio_buttons, collection: ["Yes", "No"] %>
    </div>
    <div style="display: none;" data-show-for="both">
      <%= f.button :submit, 'Get in touch', class: 'btn btn-default' %>
    </div>
<% end %>

app/views/inquiries/edit.html.erb
<h1>Edit Inquiry</h1>

<%= render 'form' %>

<%= link_to 'Show', @inquiry %> | 
<%= link_to 'Back', inquiries_path %>

app/views/inquiries/index.html.erb
<h1>Inquiries</h1>

<table>
  <thead>
    <tr>
      <th>Inquiry Type</th>
      <th>Received</th>
      <th>Name</th>
      <th>City</th>
      <th>Event Date</th>
    </tr>
  </thead>
  <tbody>
    <% @inquiries.each do |inquiry| %>
    <tr>
      <td><%= inquiry.role %></td>
      <td><%= inquiry.created_at %></td>
      <td><%= inquiry.name %></td>
      <td><%= inquiry.city %></td>
      <td><%= inquiry.date %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inquiry', new_inquiry_path %>

app/views/inquiries/new.html.erb
<h1>New inquiry</h1>

<%= render 'form' %>

<%= link_to 'Back', inquiries_path %>

app/views/inquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Inquiry Type:</strong>
  <%= @inquiry.role %>
</p>

<p>
  <strong>Date:</strong>
  <%= @inquiry.date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @inquiry.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @inquiry.city %>
</p>

<p>
  <strong>Email:</strong>
  <%= @inquiry.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @inquiry.phone %>
</p>

<p>
  <strong>License:</strong>
  <%= @inquiry.license %>
</p>

<%= link_to 'Edit', edit_inquiry_path(@inquiry) %> |
<%= link_to 'Back', inquiries_path %>

app/views/layouts/_footer.html.erb
          <div class="mastfoot">
            <div class="inner">
              <p>Waiters for Later - <%= Time.now.year %></p>
            </div>
          </div>

app/views/layouts/_header.html.erb
    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand"><%= link_to 'Waiters for Later', root_path%></h3>
              <ul class="nav masthead-nav">
                <% if current_admin_user %>
                <li><%= link_to 'Inquiries', inquiries_path %></li>
                <% end %>
              </ul>
            </div>
          </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Waiters for Later</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="initial-scale=1">
</head>
<body>
<%= render 'layouts/header' %>
  <%= yield %>
</body>
<%= render 'layouts/footer' %>
</html>

app/views/static_pages/home.html.erb
<div class="inner cover">
  <p id="notice"><%= notice %></p>
  <h1>I want to...</h1>
<%= render :partial => 'inquiries/form' %>

app/views/waiters/_form.html.erb
<%= form_for(@waiter, remote: true) do |f| %>

  <div class="form-group">
    <label class="control-label" for="name">Name</label>
    <br />
    <input type="text" name="name" class="form-control" />
    <span class="help-block"></span>
  </div>
  <div class="form-group">
    <label for="email" class="control-label">Email</label>
    <br />
    <input type="text" name="email" class="form-control" />
    <span class="help-block"></span>    
  </div>
  <div class="form-group">
    <label for="phone" class="control-label">Phone</label>
    <br />
    <input type="text" class="form-control" name="phone" />
    <span class="help-block"></span>    
  </div>
  <div class="form-group">
      <label for="city" class="control-label">City</label>
    <br />
    <input type="text" class="form-control" name="city" />
    <span class="help-block"></span>    
  </div>
  <div class="actions">
    <input type="submit" name="commit" class="btn btn-danger" value="Submit" />
  </div>

<% end %>

app/views/waiters/edit.html.erb
<h1>Editing waiter</h1>

<%= render 'form' %>

<%= link_to 'Show', @waiter %> |
<%= link_to 'Back', waiters_path %>

app/views/waiters/index.html.erb
<h1>Listing waiters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>City</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @waiters.each do |waiter| %>
      <tr>
        <td><%= waiter.name %></td>
        <td><%= waiter.email %></td>
        <td><%= waiter.phone %></td>
        <td><%= waiter.city %></td>
        <td><%= link_to 'Show', waiter %></td>
        <td><%= link_to 'Edit', edit_waiter_path(waiter) %></td>
        <td><%= link_to 'Destroy', waiter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Waiter', new_waiter_path %>

app/views/waiters/new.html.erb
<h1>New waiter</h1>

<%= render 'form' %>

<%= link_to 'Back', waiters_path %>

app/views/waiters/new.js.erb
$('div.form-group').addClass('has-error');
$('span').append('Try again.');

app/views/waiters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @waiter.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @waiter.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @waiter.phone %>
</p>

<p>
  <strong>City:</strong>
  <%= @waiter.city %>
</p>

<%= link_to 'Edit', edit_waiter_path(@waiter) %> |
<%= link_to 'Back', waiters_path %>

app/views/waiters/show.js.erb
  $('span').empty();
  $('#myWaiterModal').modal('hide');
  document.getElementById("new_waiter").reset();
  $('#successMessage').append('Waiter was successfully created.').hide(3000);